spring:
  # application configuration
  application:
    name: finstream-data-ingestion
    version: 1.0.0-SNAPSHOT

  # configuring mongodb database
  data:
    mongodb:
      database: finstream_database
      uri: ${DB_PASSWORD}

  # servlet configuration for the rest api
  mvc:
    servlet:
      path: "/v1/"
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

# springdoc openapi configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v1/v3/api-docs/swagger-config
    url: /v1/v3/api-docs
    enabled: true

# hdfs configuration
hdfs:
  uri: ${HDFS_URI:hdfs://localhost:9000}
  upload:
    path: ${UPLOAD_PATH:/finance/uploads/}
